# Generated by Django 2.2.4 on 2019-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0005_auto_20190831_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.CharField(choices=[('economics', 'Economics'), ('health', 'Health'), ('sports', 'Sport'), ('technology', 'Technology'), ('arts', 'Arts')], max_length=11, null=True),
        ),
    ]
